apiVersion: v1
kind: Service
metadata:
  labels:
    io.vaas.service: etcd
  name: etcd
spec:
  ports:
    - name: "2379"
      port: 2379
      targetPort: 2379
    - name: "2380"
      port: 2380
      targetPort: 2380
  selector:
    io.vaas.service: etcd
