apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.vaas.service: etcd
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.vaas.service: etcd
  template:
    metadata:
      labels:
        io.vaas.network/vaas-platform-network: "true"
        io.vaas.service: etcd
    spec:
      containers:
        - env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: http://etcd:2379
          image: bitnami/etcd:latest
          name: vaas-platform-etcd
          ports:
            - containerPort: 2379
              hostPort: 2379
              protocol: TCP
            - containerPort: 2380
              hostPort: 2380
              protocol: TCP
      restartPolicy: Always
