apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.vaas.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.vaas.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.vaas.network/vaas-platform-network: "true"
        io.vaas.service: minio
    spec:
      containers:
        - env:
            - name: MINIO_ROOT_PASSWORD
              value: minio-root-password
            - name: MINIO_ROOT_USER
              value: minio-root-user
          image: bitnami/minio:latest
          name: vaas-platform-minio
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
            - containerPort: 9001
              hostPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /bitnami/minio/data
              name: vaas-platform-minio-volume
      restartPolicy: Always
      volumes:
        - name: vaas-platform-minio-volume
          persistentVolumeClaim:
            claimName: vaas-platform-minio-volume
