apiVersion: v1
kind: Service
metadata:
  labels:
    io.vaas.service: vaas-platform
  name: vaas-platform
spec:
  ports:
    - name: "9080"
      port: 9080
      targetPort: 9080
  selector:
    io.vaas.service: vaas-platform
