apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: vaas-platform-minio-volume
  name: vaas-platform-minio-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
